# Generated by Django 4.1.6 on 2023-02-13 01:10

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Regular', "Regular - Can't delete members"), ('Admin', 'Admin - Can delete members')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
