# Generated by Django 4.1.6 on 2023-02-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="members",
            table="Members",
        ),
    ]
