# Generated by Django 4.1.6 on 2023-02-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_members_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="telephone",
            field=models.BigIntegerField(),
        ),
    ]
