# Generated by Django 4.1.6 on 2023-02-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_members_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="fname",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="members",
            name="lname",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="members",
            name="telephone",
            field=models.CharField(max_length=50),
        ),
    ]
