# Generated by Django 4.1.6 on 2023-02-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_members_fname_alter_members_lname_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Member",
        ),
        migrations.AlterModelTable(
            name="member",
            table=None,
        ),
    ]
