# Generated by Django 4.1.6 on 2023-02-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_rename_members_member_alter_member_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
    ]
